### ISSUE TITLE
Error importing Ofx file: incorrect dates

### ISSUE THREAD

**Issue by mdoyen** [libofx/libofx#39] opened 2021-02-06 10:47 UTC
Hi,

Relative to HomeBank bug https://bugs.launchpad.net/homebank/+bug/1886034

**the report:**
When I import an ofx file the transaction dates in all of them are 1969-12-31.
View an excerpt from the ofx file with a transaction:
```
...
  <STMTTRN>
    <TRNTYPE>DEBIT
    <DTPOSTED>20200406000000[-03:EST]
    <TRNAMT>-31.16
    <FITID>N102C0:06/04/20:-914.16:0002579: Visa Electron: Supermercado
    <CHECKNUM>0002579
    <MEMO>Visa Electron Supermercado
  </STMTTRN>
...
```

**I'm using:**
OS Type : Gnu/Linux, distribution Ubuntu 20.04
HomeBank version: 5.4.2
GTK version : 3.24.18
Libofx : libofx7:amd64, :0.9.15-3build1

**some additional infos**
- there is an ofxdump into the homebank bug report
- that is happening only for dates after 2020.09, before that date all went ok

Regards,
Maxime.

**Comment by cstim** [comment] 2021-02-12 20:26
Can you please attach an actual example file, not only an excerpt? Also, "the ofxdump on the homebank bug report" means you attached the log output from running the ofxdump program there, but this is not yet an example file. Once you attach a (small) example file so that we can reproduce this ourselves, we can probably fix this quickly.

**Comment by cstim** [comment] 2021-02-12 20:42
... and with current libofx 0.10.1 the snippet from above also doesn't show anything unusual. So maybe the error has been fixed in the meantime anyway, and you "just" have to wait until your distribution and/or homebank has updated to libofx 0.10.0 or higher.

**Comment by whistlefall** [comment] 2021-03-11 02:58
> Can you please attach an actual example file, not only an excerpt? Also, "the ofxdump on the homebank bug report" means you attached the log output from running the ofxdump program there, but this is not yet an example file. Once you attach a (small) example file so that we can reproduce this ourselves, we can probably fix this quickly.

The affected user of HomeBank (related to HomeBank bug cited by mdoyen) provided a file: https://bugs.launchpad.net/homebank/+bug/1886034/+attachment/5389720/+files/ofxdump.txt

**Comment by cstim** [comment] 2021-03-21 19:41
> The affected user of HomeBank (related to HomeBank bug cited by mdoyen) provided a file: https://bugs.launchpad.net/homebank/+bug/1886034/+attachment/5389720/+files/ofxdump.txt

Unfortunately this attached file is just the log output of the program, as I have already mentioned in the comment before. We would need an input file that reproduces this error, otherwise we cannot fix this with the information given so far.

**Comment by mdoyen** [comment] 2021-03-28 16:49
I asked the user to try it out with latest libofx if possible
and to provide a file, I'll keep you posted

**Comment by mdoyen** [comment] 2021-05-21 06:11
Hi there,

here is the sample file:
[1886034-extratoCC.ofx.zip](https://github.com/libofx/libofx/files/6520452/1886034-extratoCC.ofx.zip)

**Comment by gilbertoca** [comment] 2021-09-09 18:10
I do have this problem as well - I use [Kmymoney 5.1.1](https://github.com/KDE/kmymoney) and ofxdump 0.9.12. @mdoyen @benoitg @cstim  In my case, the ofx file has transactions beginning in August and finishing in September, but the issue occurs on August 23 to 24:
```
ofx_proc_transaction():
    Account ID : 1 1111-8 11111-1
    Transaction type: OTHER: Other
    Date posted: Mon Aug 23 12:00:00 2021 -03
    Total money amount: -22.28
    # of units: 22.28
    Unit price: 1.00
    Financial institution's ID for this transaction: 20210823122280
    Check number: 000000948541
    Reference number: 948.541
    Extra transaction information (memo): Compra com Cartão - 22/08 07:58 QUITANDA

ofx_proc_transaction():
    Account ID : 1 1111-8 11111-1
    Transaction type: OTHER: Other
    Date posted: Mon Aug 23 12:00:00 2021 -03
    Total money amount: -25.00
    # of units: 25.00
    Unit price: 1.00
    Financial institution's ID for this transaction: 20210823125000
    Check number: 000000082301
    Reference number: 82.301
    Extra transaction information (memo): PIX - Enviado - 23/08 07:59 RHT

ofx_proc_transaction():
    Account ID : 1 1111-8 11111-1
    Transaction type: OTHER: Other
    Date posted: Wed Dec 31 20:59:59 1969 -03
    Total money amount: -33.00
    # of units: 33.00
    Unit price: 1.00
    Financial institution's ID for this transaction: 20210824133000
    Check number: 000000401283
    Reference number: 401.283
    Extra transaction information (memo): Compra com Cartão - 24/08 13:52 GM

ofx_proc_transaction():
    Account ID : 1 1111-8 11111-1
    Transaction type: OTHER: Other
    Date posted: Wed Dec 31 20:59:59 1969 -03
    Total money amount: -30.00
    # of units: 30.00
    Unit price: 1.00
    Financial institution's ID for this transaction: 20210824130000
    Check number: 000000405224
    Reference number: 405.224
    Extra transaction information (memo): Compra com Cartão - 24/08 13:54 POINTD

```
Asked by @jralls 
The correspondent transactions from my ofx file:

```
<BANKTRANLIST>
   <DTSTART>20210803120000[-3:BRT]</DTSTART>
   <DTEND>20210903120000[-3:BRT]</DTEND>
...
<STMTTRN>
    <TRNTYPE>OTHER</TRNTYPE>
    <DTPOSTED>20210823120000[-3:BRT]</DTPOSTED>
    <TRNAMT>-22.28</TRNAMT>
    <FITID>20210823122280</FITID>
    <CHECKNUM>000000948541</CHECKNUM>
    <REFNUM>948.541</REFNUM>
    <MEMO>Compra com Cartão - 22/08 07:58 QUITANDA</MEMO>
</STMTTRN>
<STMTTRN>
    <TRNTYPE>OTHER</TRNTYPE>
    <DTPOSTED>20210823120000[-3:BRT]</DTPOSTED>
    <TRNAMT>-25.00</TRNAMT>
    <FITID>20210823125000</FITID>
    <CHECKNUM>000000082301</CHECKNUM>
    <REFNUM>82.301</REFNUM>
    <MEMO>PIX - Enviado - 23/08 07:59 RHT</MEMO>
</STMTTRN>
<STMTTRN>
    <TRNTYPE>OTHER</TRNTYPE>
    <DTPOSTED>20210824120000[-3:BRT]</DTPOSTED>
    <TRNAMT>-33.00</TRNAMT>
    <FITID>20210824133000</FITID>
    <CHECKNUM>000000401283</CHECKNUM>
    <REFNUM>401.283</REFNUM>
    <MEMO>Compra com Cartão - 24/08 13:52 GM</MEMO>
</STMTTRN>
<STMTTRN>
    <TRNTYPE>OTHER</TRNTYPE>
    <DTPOSTED>20210824120000[-3:BRT]</DTPOSTED>
    <TRNAMT>-30.00</TRNAMT>
    <FITID>20210824130000</FITID>
    <CHECKNUM>000000405224</CHECKNUM>
    <REFNUM>405.224</REFNUM>
    <MEMO>Compra com Cartão - 24/08 13:54 POINTD</MEMO>
</STMTTRN>
```

**Comment by jralls** [comment] 2021-09-09 18:53
@gilbertoca We need to know the corresponding <DTPOSTED> values from the OFX file for each transaction.

EDIT: Also, please test with the latest libofx 0.10.2 per @cstim's comment in February: The problem is probably fixed.

**Comment by jralls** [comment] 2021-09-09 19:03
The following from @mdoyen's file suggests that the problem might be the TRNLIST dates:
```
                              <BANKTRANLIST>
                                        <DTSTART>20210513000000[-3:GMT]
                                        <DTEND>20210513000000[-3:GMT]
                                                <STMTTRN>
                                                        <TRNTYPE>OTHER
                                                        <DTPOSTED>20210513000000[-3:GMT]
```
That's a 0 time span. @gilbertoca I suppose we need the DTSTART and DTEND values from your file as well.

**Comment by gilbertoca** [comment] 2021-09-09 19:19
@jralls, I've just edited my post. Thank you!

I forgot to mention another ERROR I've got from ofxdump (I don't know if it has relation):
```
gilberto.andrade@C430760:~/Downloads$ ofxdump extrato-30dias.ofx         
LibOFX INFO: libofx_proc_file(): File format not specified, autodetecting...
(Above message occurred on Line 18446744073709551615, Column 18446744073709551615)
LibOFX INFO: libofx_proc_file(): Detected file format: OFX (Open Financial eXchange (OFX or QFX))
(Above message occurred on Line 18446744073709551615, Column 18446744073709551615)
LibOFX STATUS: find_dtd():DTD found: /usr/share/libofx/dtd/opensp.dcl
(Above message occurred on Line 18446744073709551615, Column 18446744073709551615)
LibOFX STATUS: find_dtd():DTD found: /usr/share/libofx/dtd/ofx160.dtd
(Above message occurred on Line 18446744073709551615, Column 18446744073709551615)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SIGNONMSGSRSV1
(Above message occurred on Line 2, Column 4)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SONRS
(Above message occurred on Line 3, Column 7)
ofx_proc_status():
    Ofx entity this status is relevant to: SONRS 
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate FI
(Above message occurred on Line 10, Column 10)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate BANKMSGSRSV1
(Above message occurred on Line 16, Column 4)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate STMTTRNRS
(Above message occurred on Line 17, Column 7)
ofx_proc_status():
    Ofx entity this status is relevant to: STMTTRNRS 
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

LibOFX ERROR: OpenSP parser: otherError (misc parse error):
/tmp/libofxtmpdefkM9:41:39:E: non SGML character number 195

(Above message occurred on Line 41, Column 40)
LibOFX ERROR: OpenSP parser: otherError (misc parse error):
/tmp/libofxtmpdefkM9:41:40:E: non SGML character number 163

(Above message occurred on Line 41, Column 41)
LibOFX ERROR: OpenSP parser: otherError (misc parse error):
/tmp/libofxtmpdefkM9:68:39:E: non SGML character number 195

(Above message occurred on Line 68, Column 40)
LibOFX ERROR: OpenSP parser: otherError (misc parse error):
/tmp/libofxtmpdefkM9:68:40:E: non SGML character number 163

(Above message occurred on Line 68, Column 41)
LibOFX ERROR: OpenSP parser: otherError (misc parse error):
/tmp/libofxtmpdefkM9:77:39:E: non SGML character number 195
```

**Comment by jralls** [comment] 2021-09-09 21:24
@gilbertoca ISTR that the SGML character issue was fixed some time ago. Please get ofx-0.10.2 and try with that.

@mdoyen
```
ofxdump ~/Documents/Downloads/1886034-extratoCC.ofx
LibOFX INFO: libofx_proc_file(): File format not specified, autodetecting...
LibOFX INFO: libofx_proc_file(): Detected file format: OFX (Open Financial eXchange (OFX or QFX))
LibOFX STATUS: find_dtd():DTD found: /Users/john/Development/Gnucash-Build/Gnucash-master-git-10.13-x86_64/inst/share/libofx/dtd/opensp.dcl
LibOFX STATUS: find_dtd():DTD found: /Users/john/Development/Gnucash-Build/Gnucash-master-git-10.13-x86_64/inst/share/libofx/dtd/ofx160.dtd
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SIGNONMSGSRSV1
(Above message occurred on Line 2, Column 2)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SONRS
(Above message occurred on Line 3, Column 3)
ofx_proc_status():
    Ofx entity this status is relevant to: SONRS
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate FI
(Above message occurred on Line 10, Column 4)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate BANKMSGSRSV1
(Above message occurred on Line 16, Column 2)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate STMTTRNRS
(Above message occurred on Line 17, Column 3)
ofx_proc_status():
    Ofx entity this status is relevant to: STMTTRNRS
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

ofx_proc_account():
    Account ID: 00000  000000000
    Account name: Bank account 000000000
    Account type: CHECKING
    Default Currency: BRL
    Bank ID: 00000
    Account #: 000000000

ofx_proc_statement():
    Default Currency: BRL
    Account ID: 00000  000000000
    Start date of this statement: Thu May 13 03:59:00 2021 PDT
    End date of this statement: Thu May 13 03:59:00 2021 PDT
    Ledger balance: 2560.74
    Ledger balance date: Thu May 20 03:59:00 2021 PDT

ofx_proc_transaction():
    Account ID : 00000  000000000
    Transaction type: OTHER: Other
    Date posted: Thu May 13 03:59:00 2021 PDT
    Total money amount: -6.00
    # of units: 6.00
    Unit price: 1.00
    Financial institution's ID for this transaction: 000000
    Check number: 000000
    Payee_id: 0
    Extra transaction information (memo): PIX ENVIADO OUTRA INST - DIF TIT  AAAAAA AAAA AAAAAA

$ Manjusri:86_64/build/gnucash-git> ofxdump --version
ofxdump 0.10.2
```
 It sure looks to me that @cstim is right and this has already been fixed.

**Comment by gilbertoca** [comment] 2021-09-10 12:09
@cstim @jralls @mdoyen Unfortunately I can not find any [openSUSE repository](https://software.opensuse.org/package/libofx) with this fix (10.2). I've found version 10.1 and it has the same issue.
Is it possible to back-port the fix for version 9.x time line? (I think several apps uses this version yet)

**Comment by jralls** [comment] 2021-09-10 18:46
@gibertoca, On pasting your start-date and transactions into @mdoyen's file I get correct dates every time with ofxdump versions 0.10.2, 0.10.1 and 0.9.15; interestingly I also don't get a time error from @mdoyen's file with 0.9.15.

I was mistaken about the charset errors being fixed, that's #20. I get them too, it's from 'ã' in Cartão and since the dates work it's not that.
 
I wondered if perhaps there's a timezone issue, so I switched timezone to America/Sao_Paulo. Still works OK on macOS, including version 0.9.15. I fired up my OpenSuSE Tumbleweed VM and tested in my home America/Los_Angeles and America/Sao_Paolo. It worked in the former and failed in the latter. Tried the same on Fedora 34, which interestingly is also shipping ofx 0.9.12, and it works correctly on both. Also tested on a Windows VM--versions 0.10.2 and 0.9.14--and it also works in both timezones. Ditto Ubuntu 18.04 LTS (ofxdump 0.9.12) and ArchLinux(ofxdump 0.9.15).

This is starting to look like an openSuSE problem, but I hadn't run that VM in a while and there were a bunch of updates waiting, so I let the updater do its thing and now ofxdump is now 0.10.1 and the modified file now works correctly in America/Sao_Paolo. It seems to be an openSuSE ex-problem, but if you're not using Tumbleweed you may need to wait a while for whatever else got changed.

@mdoyen your test file also imports correctly with Ubuntu 18.04 LTS in the UTC-03 timezone. Can you make sure you're up to date on system updates and make sure you can still reproduce the issue?

**Comment by gilbertoca** [comment] 2021-09-13 14:45
@jralls Yes, it could be a locale problem in openSUSE leap 15.3. I asked for help on Kmymoney user list and Thomas has build a [appimage with the fix](https://invent.kde.org/office/kmymoney/-/commit/a3034d37b809a6d89ae5cc50ac8a06dd50e77f44), version KMyMoney-5.1.2-0af86e0-x86_64.AppImage, as Thomas indicated.

**Comment by mdoyen** [comment] 2021-10-24 12:30
@jralls : i did not reproduced the reporter bug on april (https://bugs.launchpad.net/homebank/+bug/1886034)
with ofx 0.9.15 still, ofxdump output on win ubuntu 21.10 is:

`ofxdump extratoCC.ofx 
LibOFX INFO: libofx_proc_file(): File format not specified, autodetecting...
LibOFX INFO: libofx_proc_file(): Detected file format: OFX (Open Financial eXchange (OFX or QFX))
LibOFX STATUS: find_dtd():DTD found: /usr/share/libofx7/libofx/dtd/opensp.dcl
LibOFX STATUS: find_dtd():DTD found: /usr/share/libofx7/libofx/dtd/ofx160.dtd
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SIGNONMSGSRSV1
(Above message occurred on Line 2, Column 2)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate SONRS
(Above message occurred on Line 3, Column 3)
ofx_proc_status():
    Ofx entity this status is relevant to: SONRS 
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate FI
(Above message occurred on Line 10, Column 4)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate BANKMSGSRSV1
(Above message occurred on Line 16, Column 2)
LibOFX INFO: Created OfxDummyContainer to hold unsupported aggregate STMTTRNRS
(Above message occurred on Line 17, Column 3)
ofx_proc_status():
    Ofx entity this status is relevant to: STMTTRNRS 
    Severity: INFO
    Code: 0, name: Success
    Description: The server successfully processed the request.

ofx_proc_account():
    Account ID: 00000  000000000
    Account name: Bank account 000000000
    Account type: CHECKING
    Currency: BRL
    Bank ID: 00000
    Account #: 000000000

ofx_proc_statement():
    Currency: BRL
    Account ID: 00000  000000000
    Start date of this statement: Thu May 13 04:00:00 2021 CEST
    End date of this statement: Thu May 13 04:00:00 2021 CEST
    Ledger balance: 2560.74
    Ledger balance date: Thu May 20 04:00:00 2021 CEST

ofx_proc_transaction():
    Account ID : 00000  000000000
    Transaction type: OTHER: Other
    Date posted: Thu May 13 04:00:00 2021 CEST
    Total money amount: -6.00
    # of units: 6.00
    Unit price: 1.00
    Financial institution's ID for this transaction: 000000
    Check number: 000000
    Payee_id: 0
    Extra transaction information (memo): PIX ENVIADO OUTRA INST - DIF TIT  AAAAAA AAAA AAAAAA
`
so it still correct on my machine.
I'm going to ask the reporter to try after reading this last replies

**Comment by mdoyen** [comment] 2022-01-02 17:02
Hey,

a user suggested to test with a pt_BR locale, which I did, and still don't have a problem, date is well imported and also correct with ofxdump: Date posted: Thu May 13 04:00:00 2021 CEST

so to me, from a HB perspective, we can close this bug.

**Comment by cstim** [comment] 2022-01-02 18:48
Closing as suggested. Thanks everyone for your discussion!

**Closed as completed by cstim** 2022-01-02 18:48 UTC
