### ISSUE TITLE
Account callback called for transfer accounts

### ISSUE THREAD

**Issue by benoitg** [libofx/libofx#35] opened 2020-07-23 18:13 UTC
Formerly https://sourceforge.net/p/libofx/bugs/46/ , reported by Jethro Beekman, imported here because there is a fair bit of analysis

There is currently no good way to distinguish whether an account callback is called for the account that the statement pertains to (statement account, when encountering e.g. OFX/INVSTMTMSGSRSV1/INVSTMTTRNRS/INVSTMTRS/INVACCTFROM), or an account specified as the peer in a transaction (transfer account, when encountering e.g. OFX/INVSTMTMSGSRSV1/INVSTMTTRNRS/INVSTMTRS/INVTRANLIST/INVBANKTRAN/STMTTRN/BANKACCTTO).

This breaks GnuCash as it calls gnc_import_select_account() for every account callback. Just saying "the first callback is for the statement account, later callbacks are for transfer accounts" is not sufficient, as there can be multiple statements in a single OFX file.

OfxStatementContainer::data.account_ptr and account_id are getting overwritten for every transfer account encountered which I think is a bug. Whenever a new OfxAccountContainer is created (either through a from a statement account or a transfer account), eventually OfxAccountContainer::add_to_main_tree gets called, which in turn calls OfxMainContainer::add_container(OfxAccountContainer*), which appends this account to the account tree. When the same later happens for a transaction, OfxMainContainer::add_container(OfxTransactionContainer*) looks up the last top-level account in the account tree, and calls transaction->add_account with that as an argument. This is wrong, because it should have been the statement account. I'm not sure what the benefit is of having the transfer accounts as top-level accounts in the tree, or perhaps this is the bug?

The attached patch just ignores transfer accounts, which works for my purposes but might not be the correct fix.

**Comment by jralls** [comment] 2020-07-23 20:24
@benoitg you seem to have blown up the sourceforge bug tracker by setting the issues redirect to here: Now all of the old bug links including the one above 404.

**Comment by jethrogb** [comment] 2020-07-24 07:58
Here's the patch from the original ticket:
```diff
--- a/lib/ofc_sgml.cpp	2011-03-30 15:30:50.000000000 -0700
+++ b/lib/ofc_sgml.cpp	2014-07-16 02:35:36.226070545 -0700
@@ -171,7 +171,10 @@
                identifier == "ACCTFROM" )
       {
         message_out (PARSER, "Element " + identifier + " found");
-        curr_container_element = new OfxAccountContainer (libofx_context, curr_container_element, identifier);
+        if (curr_container_element->type == "STATEMENT")
+            curr_container_element = new OfxAccountContainer (libofx_context, curr_container_element, identifier);
+        else
+            curr_container_element = new OfxDummyContainer (libofx_context, curr_container_element, identifier);
       }
       else if (identifier == "SECINFO")
       {
--- a/lib/ofx_sgml.cpp	2011-04-03 09:27:15.000000000 -0700
+++ b/lib/ofx_sgml.cpp	2014-07-16 02:35:21.386071076 -0700
@@ -177,7 +177,10 @@
       else if (identifier == "BANKACCTFROM" || identifier == "CCACCTFROM" || identifier == "INVACCTFROM")
       {
         message_out (PARSER, "Element " + identifier + " found");
-        curr_container_element = new OfxAccountContainer (libofx_context, curr_container_element, identifier);
+        if (curr_container_element->type == "STATEMENT")
+            curr_container_element = new OfxAccountContainer (libofx_context, curr_container_element, identifier);
+        else
+            curr_container_element = new OfxDummyContainer (libofx_context, curr_container_element, identifier);
       }
       else if (identifier == "SECINFO")
       {
```

**Comment by jeffjl74** [comment] 2020-11-03 15:57
This issue is fixed in my enhanced-investments pull request

**Comment by cstim** [comment] 2021-01-02 23:05
Thanks to @jeffjl74 improvements, the issue is now fixed in master and upcoming versions.

**Closed as completed by cstim** 2021-01-02 23:05 UTC
